inputs:
  python-version:
    required: false
    default: 3.9
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1.3
      with:
        virtualenvs-in-project: true
    - uses: actions/cache@v2
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-abc
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction
      shell: bash
    # - name: activate
    #   run: source .venv/bin/activate
    #   shell: bash
