name: black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: ./.github/actions/python_setup
      - name: Run black with review dog
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          black_args: "--diff --line-length 100"
          fail_on_error: true
