name: black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: ./.github/actions/python_setup
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
      - run: |
          python -m pip install black
      - name: Run black with review dog
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          black_args: "--diff --line-length 100"
          fail_on_error: true
