name: flake8

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: ./.github/actions/python_setup
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
      - run: |
          python -m pip install flake8 flake8-docstrings flake8-quotes flake8-bugbear
      - name: Run flake8 with review dog
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
