name: flake8

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: ./.github/actions/python_setup
      - name: activate
        run: source .venv/bin/activate
      - name: Run flake8 with review dog
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
