name: pyright

on: [push]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: ./.github/actions/python_setup
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install pyright
        run: npm install --global pyright
      - name: Lint with pyright
        run: pyright
