name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: ./.github/actions/python_setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: set up poetry
        uses: ./.github/actions/poetry_setup
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest
